### ISSUE TITLE
LICENSE file needs file extension

### ISSUE THREAD

**Issue by decentjohn** [simpkins/de1plus-mqtt#2]
Could you rename LICENSE to LICENSE.txt ?

The update mechanism needs a file name extension on all files.

**Comment by simpkins** [comment]
Sure, I can rename it.  Actually, since the main de1app code is GPLv3 licensed I probably should also fix this license file to also use GPLv3 rather than the current MIT license.

I see several other plugins have `LICENSE` files that simply aren't listed in `de1plus/misc.tcl`.  I assume you skip those since they are GPLv3, which is the same as the main de1app code? (e.g., https://github.com/ebengoechea/de1app_plugin_SDB, https://github.com/vjapolitzer/de1app_plugin_keyboard_control, https://github.com/bkeller2/old_lcd_disable).

**Comment by decentjohn** [comment]
Yah, the http update needs filename extensions, and yes, everything should be GPL3, so we keep things simple.

**Comment by decentjohn** [comment]
Should the settings file be sent as part of the update, or does your plugin create it if it's not there?

**Comment by simpkins** [comment]
The plugin will create the settings.tdb file if it isn't present, so it doesn't need to be included in the update.

The settings.tdb file that is provided is just an example template, as a couple settings cannot be edited in the UI and so users need to manually edit the settings.tdb file if they want to enable these features.  In particular, in order to enable TLS certificate validation users need to also copy a CA certificate file to their tablet, and edit settings.tdb to contain the path to this file.
